# Generated by Django 3.1.7 on 2021-03-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='seller_id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
