# Generated by Django 3.1.7 on 2021-03-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210328_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='salesman',
            old_name='seller',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='id',
        ),
        migrations.AddField(
            model_name='salesman',
            name='seller_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
