# Generated by Django 3.1.7 on 2021-04-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210329_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/pictures'),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='count_sells',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesman',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
