# Generated by Django 3.1.7 on 2021-04-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0002_auto_20210329_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
