# Generated by Django 3.1.7 on 2021-03-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210328_2241'),
        ('sells', '0002_auto_20210328_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='id_salesman',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.salesman'),
        ),
    ]
