# Generated by Django 3.1.7 on 2021-03-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0003_sells_id_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='invoice_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
