# Generated by Django 3.1.7 on 2021-04-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='customer',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
