# Generated by Django 3.1.7 on 2021-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210328_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id_product',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
